### ISSUE TITLE
Quicklisp Update 

### ISSUE THREAD

**Issue by alexpopov** [vindarel/cl-str#10]
This version (0.6) does not get pulled through Quicklisp; version 0.1 does. 

If pushing the latest version to Quicklisp is time consuming but possible by outsiders, I could take it on.

**Comment by tdrhq** [comment]
yes please! I just came here looking for this too

**Comment by vindarel** [comment]
Damn you're horribly right. But we are not supposed to push newer versions to Quicklisp, I don't know what's happening here.
In the meanwhile you can clone this lib into `~/quicklisp/local-projects/` and quickload it normally.

Thanks for the notification !

**Comment by vindarel** [comment]
Ahem, I reproduced better and it works fine actually (just tried in a new environment, Portacle). Did you

    (ql:update-dist "quicklisp")

?

**Comment by tdrhq** [comment]
@vindarel oh dang, yeah that works for me :) Thanks!

**Comment by vindarel** [comment]
phew

I prefer to think about QL as apt-get rather than pip/npm/whatever. That way upgrading makes sense :) (and it's a sanier model too)
