### ISSUE TITLE
Next release 0.20

### ISSUE THREAD

**Issue by kilianmh** [vindarel/cl-str#107]
Since the last tag, there were quite [many commits](https://github.com/vindarel/cl-str/compare/0.19...master) and almost 3 years so probably enough for a next release.

Any thing coming to your mind that should be done before? @vindarel

Here are some changes that could be included in tag description:

- type declaration e.g. for `concat`,` join`
- new: `rsplit` `ascii-p` `ascii-char-p` `fit` `ensure` `ensure-prefix` `ensure-suffix` `ensure-wrapped-in` `wrapped-in-p` `*whitespaces*`
- speed up `join`
- more functions now work with characters as well
- use uninterned symbols in `defpackage`
- fix `style-warnings`
- deprecate predicates ending with `?`
- `trim` works now with arbitrary values
- make casing-functions consistent to inbuilt cl casing functions
- Switch testing framework to `fiveam`
- `count` case sensitivity parameter
- `string-case` body now implicit `progn`
- reimplement `replace-using`
- `regex` option for replace-functions

**Comment by vindarel** [comment]
Nice list :) I'll have to write the obligatory blog post. 

LGTM :rocket:

**Comment by kilianmh** [comment]
Fixed in https://github.com/vindarel/cl-str/commit/8e21ad1b9f13d5b254809bc95fd2be0e3d5d7f69
