### ISSUE TITLE
Quicklisp loads outdated version of cl-str

### ISSUE THREAD

**Issue by github-reader** [vindarel/cl-str#109]
Hello Supporters

Hopefully I am here on the right place. If not, please leave a notice. Specify the responsible persons if known.
I have found that Quicklisp loads version cl-str-20210531-git. It contains old code of all trim functions. The old functions only accept one parameter, the string but nothing else.

E.g. from str.lisp:

(defun trim-left (s) 
  "Remove whitespaces at the beginning of s. "
  (when s
    (string-left-trim *whitespaces* s)))

I have cloned the current version from Github master and it works fine with parameter char-bag.

Best Regards
Peter

**Comment by vindarel** [comment]
Hello, you probably have a Quicklisp dist from this date. QL works with releases, à la apt/debian releases, not like pip or npm.

```lisp
(ql-dist:version (ql-dist:find-dist "quicklisp"))
```

to update the dist and all libraries:

        (ql:update-dist "quicklisp")

https://www.quicklisp.org/beta/#basic-commands

**Comment by github-reader** [comment]
Thank you very much for your help. The update was successfull and the lib now works as expected.
