### ISSUE TITLE
failed to split a string ends with "x" by "xx"

### ISSUE THREAD

**Issue by wukgdu** [vindarel/cl-str#18]
`(str:split "xx" "asdxfghx")` returns `NIL`
```
* (str:split "xx" "asdxfghx")

NIL
```
expect: `("asdxfghx")`
```
* (cl-ppcre:split "xx" "asdxfghx")

("asdxfghx")
```
---
Reason:
`(if (string-equal separator #\x) "y" "x"))` will add "x" to the string
then `(res (butlast (cl-ppcre:split (cl-ppcre:quote-meta-chars (string separator)) val)))` will become:
```
* (cl-ppcre:split "xx" "asdxfghxx")

("asdxfgh")
```
and `butlast` gets `NIL`

---

 `(str:split "xx" "asdxfghxxx")` and `(str:split "xx" "asdxxfghx")` get wrong results, too.

**Comment by vindarel** [comment]
Thank you.

Consequently we stop trying to fix `cl-ppcre` little inconsistency, that is it doesn't return a trailing `""` when the separator appears at the end.
