### ISSUE TITLE
Inconsistent behaviour of SPLIT

### ISSUE THREAD

**Issue by lokedhs** [vindarel/cl-str#2]
The function `SPLIT` returns empty parts as an empty string. However, any empty parts at the end of the string are missing.

To reproduce:

```
(str:split #\, ",a,b,,c,")
("" "a" "b" "" "c")
```

Expected:

```
("" "a" "b" "" "c" "")
```

**Comment by vindarel** [comment]
Hi, 
the split function actually relies entirely on `cl-ppcre:split`, like this:

```
(defun split (separator s)
  "Split s into substring by separator (a regex)."
  (cl-ppcre:split separator s))
```

which returns the same result:

    (cl-ppcre:split #\, ",a,b,,c,")
    ;; => ("" "a" "b" "" "c")

So I'm likely to leave it as is (will add the optional `omits-nulls` parameter though).

I don't know the rational of this result (you're welcome to ask them :) )

It's true that the expected behavior (like `s.el` which I gave as reference does) is to have a trailing `""`.

**Comment by lokedhs** [comment]
That indeed looks like a problem with cl-ppcre. I'd suggest working around that issue by doing something like this, which will also deal with the problem where the separator is a regex control:

```
(defun split (separator s)
  (let ((v (concatenate 'string s (string separator) (if (eql separator #\x) "y" "x"))))
    (butlast (cl-ppcre:split (cl-ppcre:quote-meta-chars (string separator)) v))))
```

**Comment by vindarel** [comment]
> which will also deal with the problem where the separator is a regex control

this is indeed needed.

Thanks, I'll have a look !

**Comment by lokedhs** [comment]
I'll also recommend putting a `(check-type separator character)` in there, as otherwise things could be confusing. At least my version isn't well prepared to handle a separator which is not a character.

**Comment by vindarel** [comment]
your suggestion works fine, and it appears to work also with string separators:

      (is '("foo" "bar" "") (split "NO" "fooNObarNO") "separator is a string")

do you want to double-check / discuss it again before we close the issue ?

**Comment by lokedhs** [comment]
At the very least you need to change the call to `eql` to `string=`. Otherwise things will break if you use `"x"` as separator.
