### ISSUE TITLE
Fails to load system via asdf of LispWorks

### ISSUE THREAD

**Issue by tdrhq** [vindarel/cl-str#34]
It looks like the UTF-8 characters in the README.me are tripping up this line in the asd file:

```
#.(uiop:read-file-string
     (uiop:subpathname *load-pathname* "README.md"))
```

So far I haven't been able to work around it except by deleting the UTF-8 characters from the readme. It crashes with an error saying xyz of type character is not of type base-char.

I tried passing in :element-type 'character to read-file-string, but that's causing the same issue.

I might send in a pull request to fix this, but in the meantime I'd appreciate any hints for me to try.

**Comment by tdrhq** [comment]
full error message:
Backtrace [because of error: Error while trying to load definition for
                             system str from pathname
                             /home/.../src/third-party/cl-str/str.asd:
                             #\â\200¦ (of type character) is not of type base-char.]:

**Comment by vindarel** [comment]
What's this ASDF version? Does it have the asdf-unicode feature? (`(featurep :asdf-unicode)`)

I have `(setf sb-impl::*default-external-format* :utf-8)` in my sbclrc, you might want a similar setting?

Then I suggest to explore UIOP, we'll maybe find an utf-8 setting (`uiop:*default-encoding*`, asdf-encodings,…)

**Comment by travv0** [comment]
@tdrhq add `(lw:set-default-character-element-type 'character)` to `~/.lispworks`.

**Comment by tdrhq** [comment]
@travv0 Yep somebody from LW eventually told me that too. Thanks!
