### ISSUE TITLE
request: domain-name-p/domain-name?

### ISSUE THREAD

**Issue by compufox** [vindarel/cl-str#40]
thought some kind of predicate to see if a string contains a domain-name or a url would be nice!

**Comment by vindarel** [comment]
mmh this seems to bypass cl-str's domain. Don't you want a url-handling library like quri? see parse-uri: https://github.com/fukamachi/quri#function-parse-uri

**Comment by compufox** [comment]
thats understandable! 

to clarify: my request isnt so much parsing or manipulating a domain name, but just running a regex to determine if a string contains a domain name. ive found that quri, if not given a full proper uri, will return bad data, hence me requesting here!

thanks for looking at this :)

**Comment by alphapapa** [comment]
How would you determine whether a string contains a domain name without either having a database of domains or making a network request?  Here's a string that contains a domain name: `What is the point? I assume this.is it.`  Here's a string that does not: `thi.sis`.

**Comment by compufox** [comment]
thats a good point! Yeah I guess I was only thinking of a specific use case.
