### ISSUE TITLE
Wrong example in README

### ISSUE THREAD

**Issue by cage2** [vindarel/cl-str#44]
Hi  vindarel!

How you doing? I hope you are fine! :)

i think the example for `replace-first` was wrong:

https://github.com/vindarel/cl-str#replace-first-old-new-s

it is the same as `replace-all`

Bye!
C.

**Comment by vindarel** [comment]
Hello, and good catch! Crazy how different pairs of eyes can miss obvious things.

I'm doing well thanks, locked down in good conditions. Hope you too, glad to see you lisping, and with `str` :)

**Comment by cage2** [comment]
On Fri, Apr 03, 2020 at 10:07:29AM -0700, vindarel wrote:
> Hello,

Hi vindarel!

> and good catch! Crazy how different pairs of eyes can miss obvious things.

yes, i am still  surprised how people are able to  find bugs so deeply
hidden (for the developer) in the code :)

>
> I'm doing well thanks, locked down in good conditions.

This is the most important thing.

> Hope you too,

I am fine  but the lockdown is a bit stressful, but i think  it is the
same for everyone.

> glad to see you lisping,

I have plenty of time to spend at home. :)

> and with `str` :)

Yes, this is an useful library i just wish i knew about it before! :)

Take care!
C.
