### ISSUE TITLE
Request: replace-pairs

### ISSUE THREAD

**Issue by vindarel** [vindarel/cl-str#47]
```
(defun replace-pairs (pairs str)
  "Replace all associations in pairs (plist) and return a new string.

  Example:
  (replace-pairs (list \"{{phone}}\" \"987\") \"call {{phone}}\")
  =>
  \"call 987\""
  (assert (consp pairs))
  (dotimes (i (- (length pairs)
                 1))
    (setf str (str:replace-all (nth i pairs) (nth (incf i) pairs) str)))
  str)

#+nil
(progn
  (assert (string-equal
           "call 987"
           (replace-pairs (list "{{phone}}" "987") "call {{phone}}")))
  (assert (string-equal
           "Hi Alice call 987"
           (replace-pairs (list "{{phone}}" "987"
                                "{{name}}" "Alice")
                          "Hi {{name}} call {{phone}}"))))
```

**Comment by vindarel** [comment]
@all: Any thought on the function name? Thanks.

We already have `replace-all`, that takes *one* string to replace. `s.el` defines `replace` for this, and `replace-all` is our `replace-pairs`. We can't really have one single function since their arity is different.

**Comment by anticrisis** [comment]
On first read of the name, I expected `replace-pairs` to operate on pairs in the destination, not that `pairs` would refer to the form of the input to the algorithm. Maybe `replace-with` or `replace-by` or `replace-using`, or any of those with a `-pairs` suffix?

**Comment by vindarel** [comment]
mmh thanks. So maybe `replace-using`.
