### ISSUE TITLE
Split tests into separate system

### ISSUE THREAD

**Issue by sjl** [vindarel/cl-str#5]
Currently the main code and the tests all live in the same ASDF system.  This means that if you want to use `cl-str` you need to load `prove` and all its dependencies (`("cl-ansi-text" "cl-colors" "alexandria" "uiop")`) even if you never want to run the tests.

If the tests were split into their own system users would only have to load `prove` and friends when they want to actually run the test suite.  An example of how this can work is here:

https://github.com/sjl/cl-digraph/blob/master/cl-digraph.asd
https://github.com/sjl/cl-digraph/blob/master/cl-digraph.test.asd

I'm happy to send a PR that does the splitting, if you want it.

**Comment by vindarel** [comment]
Oh, you are so right. I obviously did not know that back then and didn't use a project generator. I would merge the PR right away.

ps: did you write about your experience with CL and Clojure ? I don't know of feedback from people who have used both. I'm personally interested in the differences of workflow. So if you feel like it, a blog post on a gist is enough !

**Comment by vindarel** [comment]
done by https://github.com/vindarel/cl-str/pull/6
