### ISSUE TITLE
Ftype str:concat, etc.

### ISSUE THREAD

**Issue by Ambrevar** [vindarel/cl-str#51]
The following 
```lisp
(declaim (ftype (function (quri:uri) string) schemeless-url))
(defun schemeless-url (uri)
  "Return URL without its scheme (e.g. it removes 'https://')."
  (str:concat (quri:uri-authority uri)
              (or (quri:uri-path uri) "/")
              (quri:uri-query uri)
              (quri:uri-fragment uri)))

```

yields

```lisp
    Type assertion too complex to check:
    (VALUES STRING &REST T).
    It allows an unknown number of values, consider using
    (VALUES STRING &OPTIONAL).

```

This is because `concatenate` is too complex to type check for SBCL.
You can fix it by adding an `ftype` to str:concat and maybe wrapping the return value with

```
(the (values string &optional)
    YOUR-RESULT)
```

Same with str:join, str:insert, all functions that use `concatenate`.

**Comment by vindarel** [comment]
The ones in https://github.com/vindarel/cl-str/pull/60 seem to do the trick.

I didn't use the `(the (values …` trick, curious what it adds.
