### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by K1D77A** [vindarel/cl-str#70]
Consider adding a few basic regex's for validating emails? 
Perhaps a regex like:  "^[^@\s]+@[^@\s]+\.[^@\s]+$"

Thanks.

**Comment by vindarel** [comment]
Hello, I really think this should go in a library of its own!

Look, there's an attempt of 800 lines here, a port from a PHP lib: https://github.com/automaticit/cl-isemail/blob/master/isemail.lisp

also darts.lib.email-address in Quicklisp. https://github.com/deterministic-arts/DartsCLEmailAddress
