### ISSUE TITLE
UIOP:DEFINE-PACKAGE :REEXPORT

### ISSUE THREAD

**Issue by phoe** [vindarel/cl-str#72]
https://github.com/vindarel/cl-str/blob/a833fa23bfaeadffdca46776bb67a562c7bb77d3/str.lisp#L20

You can use `uiop:define-package`'s `:rexport` option, since UIOP is presumed to be always available.

**Comment by vindarel** [comment]
Thanks. IIRC we don't re-export all symbols, so I might leave the manual import/export as is and change this comment. cl-reexport has :exclude and :include options which I don't see on uiop's :reexport side. Will double-check.

**Comment by vindarel** [comment]
closing in favor of existing #50
