### ISSUE TITLE
Switch testing library

### ISSUE THREAD

**Issue by kilianmh** [vindarel/cl-str#94]
The testing library should be changed, since [prove](https://github.com/fukamachi/prove) is archived.
One obvious candidate would be [fiveam](https://github.com/lispci/fiveam). Or is there another one that might be used?

**Comment by vindarel** [comment]
That's a pending task indeed. Our current system works© but a change will be necessary.

\+1 for fiveam.

https://fiveam.common-lisp.dev/docs/index.html
